name: pixelchat
description: PixelChat - Gemini AI Sohbet Uygulamasi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  mime: ^2.0.0
  path: ^1.9.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
